add_subdirectory("calculator")
add_subdirectory("sizing")
add_subdirectory("string_check")
add_subdirectory("random_fill")
add_subdirectory("complex_app")
add_subdirectory("template_utils")
add_subdirectory("tabulate")
add_subdirectory("entity_model")
add_subdirectory("bits")
add_subdirectory(zip_guard)
add_subdirectory(box_class)
add_subdirectory(catalog_app)
add_subdirectory(restaurant_app)
add_subdirectory(geometry_2d)
add_subdirectory(bank_account_app)
add_subdirectory(matrix_class_implementation)
add_subdirectory(order_management_system_app)
add_subdirectory(triangular_matrix_impl_app)
add_subdirectory(phone_manager_app)